import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Input} from '@/components/Input'
import {useRef, useState} from 'react'
import {JoinButton} from '@/components/JoinButton'
import {useWebrtc} from '@/hooks/useWebrtc'

const inter = Inter({subsets: ['latin']})

export default function Home() {

    const videoRef = useRef<HTMLVideoElement>(null)
    const peerVideoRef = useRef<HTMLVideoElement>(null)
    const { room, setRoom, joinRoom } = useWebrtc(videoRef, peerVideoRef)

    const handleChange = (value: string) => {
        setRoom(value)
    }

    const handleClick = () => {
        joinRoom(room)
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Input onChange={handleChange} value={room}/>
                <JoinButton onClick={handleClick}/>
                <div>
                    <h3>User Video</h3>
                    <video ref={videoRef}></video>
                </div>
                <div>
                    <h3>Peer Video</h3>
                    <video ref={peerVideoRef}></video>
                </div>
            </main>
        </>
    )
}
